【Fixed】万葉課題のStep4の実装
tomomiogino/everyleaf_exam pull request #4
Opened 2020-12-26 05:39 UTC by tomomiogino

万葉課題のStep4を下記の通り実装いたしました。

- ユーザモデルを作成
- ユーザとタスクを紐づけ
- ログイン、ログアウト機能を実装
- ログインをせずにタスク一覧のページに飛ぼうとしたときは、ログインページに遷移させる
- 自分が作成したタスクだけを表示させる
- ユーザの新規登録画面、ログイン画面、詳細・マイページ（show）画面を作成
- ユーザ新規登録をしたとき、同時にログインもさせる
- ログインしているときは、ユーザの新規登録画面（new画面）に行かせないようにコントローラで制御
- 自分以外のユーザのマイページ（userのshow画面）にアクセスしたらタスク一覧に遷移させる
- 管理画面を追加
- 管理画面でユーザ一覧表示・作成・更新・削除ができる
- ユーザを削除したら、そのユーザに紐づいているタスクを全て削除する
- ユーザの一覧画面で、そのユーザに紐づいているタスクの数を表示
- ユーザが作成したタスクの一覧を、そのユーザのマイページで見られる
- 管理ユーザだけがユーザ管理画面にアクセスできる
- ユーザ管理画面でロールの付与と削除ができる
- 管理ユーザが一人もいなくなってしまわないように、モデルのコールバックを利用して更新・削除の制御
- System Specテスト実装

2020-12-26 10:00 UTC, yuji91 requested changes
コードレベルでの指摘を行いましたが、課題の要件は満たしているので修正は任意です。
そのまま次の課題に進んでも問題ありません。

2020-12-26 10:00 UTC, yuji91 commented on db/seeds.rb
> +             email: "hogehoge@hoge.com",
存在しないドメインである`@example.com`を使った方がメールの誤送信の心配が無くなります。
```suggestion
             email: "hogehoge@example.com",
```

2020-12-26 10:00 UTC, yuji91 commented on app/models/user.rb
> +  def last_admin_user_update?
?で終わるメソッドはtrueかfalseのBooleanの値を返すように読み手に誤解を与えます。
`leave_last_admin`や`forbid_last_admin_update`などのメソッド名の方が良いと思います。

2020-12-26 10:00 UTC, yuji91 commented on app/controllers/sessions_controller.rb
> +  end
メソッドの中身がないアクション（renderのみを実行）は1行で記載すると中身の記載忘れでないことを明示できます。
```suggestion
  def new; end
```

2020-12-26 10:00 UTC, yuji91 commented on app/controllers/application_controller.rb
> +      if current_user.id != Task.find(params[:id].to_i).user_id
if文のネストは出来るだけ避けた方が良いです。
1行が長くなるのが嫌な場合は、判定部分をメソッドに切り出しても良いです。
```suggestion
    if current_user.admin == false && task.owner?(current_user)
```

2020-12-26 10:00 UTC, yuji91 commented on app/controllers/admin/users_controller.rb
> +    # binding.pry
消し忘れが残っていました。

2020-12-26 10:00 UTC, yuji91 commented on app/controllers/admin/users_controller.rb
> +  before_action :require_admin
コールバックとアクションの間は改行した方が見やすいですね。

2020-12-26 15:27 UTC, tomomiogino commented on db/seeds.rb
> +             email: "hogehoge@hoge.com",
ご指摘ありがとうございます。
修正いたしました。7740418

2020-12-26 15:35 UTC, tomomiogino commented on app/models/user.rb
> +  def last_admin_user_update?
命名、大事ですね。。修正いたしました。
22cc077

2020-12-26 15:38 UTC, tomomiogino commented on app/controllers/sessions_controller.rb
> +  end
こんな書き方ができるのですね。大変勉強になりました。
こちらも修正いたしました。
37a2ac4

2020-12-26 15:45 UTC, tomomiogino commented on app/controllers/application_controller.rb
> +      if current_user.id != Task.find(params[:id].to_i).user_id
実装して満足してしまい全く気にしておりませんでした。。
ご指摘ありがとうございます。修正いたしました。
99329a2

2020-12-26 15:47 UTC, tomomiogino commented on app/controllers/admin/users_controller.rb
> +    # binding.pry
見直しが甘かったです。。修正いたしました。
0da7eda

2020-12-26 15:47 UTC, tomomiogino commented on app/controllers/admin/users_controller.rb
> +  before_action :require_admin
ご指摘ありがとうございます。修正いたしました。
ce8873b

2020-12-26 15:56 UTC, tomomiogino commented
フィードバックいただいた箇所を修正いたしました。
改めましてご確認の程、よろしくお願いいたします。

2020-12-28 02:18 UTC, yuji91 approved these changes

2020-12-28 11:26 UTC, merged